# Generated by Django 3.2.15 on 2022-08-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_extention',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_url',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='myfiles'),
        ),
    ]
